services:
  node0:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: ['0', 'leader']
    networks:
    - edge-0-1
  node1:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: ['1']
    networks:
    - edge-0-1
networks:
  edge-0-1:
